# https://pub.dev/packages/pedantic_mono
include: package:pedantic_mono/analysis_options.yaml

analyzer:
  plugins:
    - custom_lint
  exclude:
    - "**/*.freezed.dart"
    - "**/*.g.dart"
    - "**/*.gr.dart"
    - "**/*.mocks.dart"
  errors:
    invalid_annotation_target: ignore

linter:
  rules:
    lines_longer_than_80_chars: false
