# include: package:flutter_lints/flutter.yaml
include: package:pedantic_mono/analysis_options.yaml

linter:
  rules:
    use_build_context_synchronously: false
    lines_longer_than_80_chars: false

analyzer:
  errors:
    invalid_annotation_target: ignore
  exclude:
    - "**/*.freezed.dart"
    - "**/*.g.dart"
