targets:
  $default:
    builders:
      source_gen|combining_builder:
        options:
          build_extensions:
            "{{dir}}/{{file}}.dart": "{{dir}}/{{file}}.g.dart"
          include:
            - lib/**/*.dart
      freezed:
        options:
          build_extensions:
            "{{dir}}/{{file}}.dart": "{{dir}}/{{file}}.freezed.dart"
          include:
            - lib/**/*.dart
