name: social_doge
version: 0.0.1+1
publish_to: none
description: Twitter follow/follower manager

environment:
  sdk: ">=2.19.6 <4.0.0"

dependencies:
  cached_network_image: ^3.2.3
  collection: ^1.17.0
  cupertino_icons: ^1.0.5
  dio: ^5.1.1
  drift: ^2.9.0
  fl_chart: ^0.63.0
  flutter:
    sdk: flutter
  flutter_inappwebview: ^5.7.2+3
  flutter_localizations:
    sdk: flutter
  flutter_riverpod: ^2.3.2
  intl: ^0.18.0
  json_annotation: ^4.8.0
  logger: ^1.3.0
  package_info_plus: ^4.0.2
  path: ^1.8.3
  path_provider: ^2.0.15
  riverpod_annotation: ^2.0.1
  shared_preferences: ^2.0.15
  sqflite: ^2.2.7
  sqlite3_flutter_libs: ^0.5.15
  twitter_openapi_dart: ^0.0.4
  twitter_openapi_dart_generated: any
  url_launcher: ^6.1.11

dev_dependencies:
  build_runner: ^2.3.3
  custom_lint: ^0.4.0
  drift_dev: ^2.9.0
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  json_serializable: ^6.6.1
  pedantic_mono: any
  riverpod_generator: ^2.1.3
  riverpod_lint: ^1.1.5

flutter:
  uses-material-design: true
  generate: true
